apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: tx-analytics
spec:
  selector:
    app: producer
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: tx-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: tx-analytics/producer:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: tx-config
            - secretRef:
                name: tx-secrets
            - secretRef:
                name: aws-credentials
                optional: true
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx320m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
          resources:
            requests:
              memory: 450Mi
              cpu: 150m
