apiVersion: v1
kind: Service
metadata:
  name: query-api
  namespace: tx-analytics
spec:
  type: NodePort
  selector:
    app: query-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-api
  namespace: tx-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-api
  template:
    metadata:
      labels:
        app: query-api
    spec:
      containers:
        - name: query-api
          image: tx-analytics/query-api:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: tx-config
            - secretRef:
                name: tx-secrets
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx384m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
          resources:
            requests:
              memory: 500Mi
              cpu: 150m
