spring:
  application:
    name: producer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: producer-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.ekruminis.txanalytics.wire.RunCommand
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      linger-ms: 20
      batch-size: 65536
      compression-type: lz4
      acks: all
      buffer-memory: 67108864
      properties:
        spring.json.add.type.headers: false
        enable.idempotence: true
        max.block.ms: 300000
        delivery.timeout.ms: 300000
        request.timeout.ms: 60000

producer:
  input-dir: ../simulation/input
  s3:
    region: eu-west-2
    endpoint-override: ""

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      service: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
