spring:
  application:
    name: producer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      linger-ms: 20
      batch-size: 65536
      compression-type: lz4
      acks: "1"
      buffer-memory: 67108864
      properties:
        spring.json.add.type.headers: false

producer:
  input-file: ../simulation/input/txs-week.json
  seed: 12345
  partitions: 3
  pacing:
    mean-tx-per-cycle: 2471
    alpha: 0.02